services:
  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq-gouser
      restart: always
      ports:
        - ${RABBITMQ_PORT}
        - ${RABBITMQ_PORT2}
      volumes:
        - ${RABBITMQ_VOLUME}
      environment:
        - DEFAULT_USER= ${DEFAULT_USER}
        - DEFAULT_PASS= ${DEFAULT_PASS}
  postgres:
    build:
      context: .
      dockerfile: .dockerfile
    image: github.com/elizeus/golang
    container_name: postgres-container
    restart: unless-stopped
    tty: true
    ports:
      - ${POSTGRES_PORT}

    environment:
      - POSTGRES_DB= ${POSTGRES_DB}
      - POSTGRES_USER= ${POSTGRES_USER}
      - POSTGRES_PASSWORD= ${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_VOLUME}

  pgadmin4:
    image: "dpage/pgadmin4:latest"
    ports:
      - ${PGADMIN4_PORT}
    volumes:
      - ${PGADMIN4_VOLUME}
    environment:
      - PGADMIN_DEFAULT_EMAIL= ${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD= ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
volumes:
  gouser: